[package]
name = "vest-plus"
version = "0.1.0"
edition = "2021"

[dependencies]
vstd = "0.0.0-2026-01-04-0057"

[package.metadata.verus]
verify = true

[package.metadata.verus.ide]
extra_args = "--expand-errors"
