[package]
name = "vest_lib"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "VestLib: Parser and serializer combinators"
repository = "https://github.com/secure-foundations/vest"
readme = "../README.md"
keywords = ["vest", "parsing", "combinators"]
categories = ["development-tools", "parsing"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]

