[package]
name = "vest_lib"
version = "0.0.0-2025-11-03-2103"
edition = "2021"
license = "MIT"
description = "VestLib: A library of formally verified parser and serializer combinators"
repository = "https://github.com/secure-foundations/vest"
readme = "../README.md"
keywords = ["vest", "verus", "verification", "parsing", "combinators"]
categories = ["development-tools", "parsing"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
verus_builtin = "0.0.0-2025-08-12-1837"
verus_builtin_macros = "0.0.0-2025-08-12-1837"
vstd = "=0.0.0-2025-08-12-1837"

[package.metadata.verus]
verify = true

[package.metadata.verus.ide]
extra_args = "--expand-errors"
