[package]
name = "opt-example"
version.workspace = true
edition.workspace = true

[dependencies]
vstd.workspace = true
vest_lib.workspace = true

[package.metadata.verus]
verify = true

[package.metadata.verus.ide]
extra_args = "--expand-errors"
